### PR TITLE
Added several SmackJeeves Comics

### PR DESCRIPTION
**Pull request by acaranta**
Added several SmackJeeves Comics

### CODE REVIEW

**Comment by TobiX** [comment]
Did you check with the scripts/smackjeeves.py update script?

**Comment by TobiX** [comment]
Thanks for your contribution! I fixed some minor things in 51ed898f5d26947647383c934de3b24827341c24.

**Comment by acaranta** [comment]
damn... no i did not check the update script, sorry :(
and thanks for your fixes

**Comment by TobiX** [comment]
Not to worry, the update scripts adds so many comics I'm currently not really using it - only as a reference...

**Pull request merged**
