### PR TITLE
Fixed pull request

### PR DESCRIPTION
**Pull request by DirkReiners**

### CODE REVIEW

**Comment by TobiX** [comment]
Thanks for your contribution. Since this contains multiple topics, I have cherry-picked the ones which are okay. Please rebase your branch if you want me to merge them in the future - I would suggest splitting different topics into multiple pull requests for better review. With that said:

- [ ] The SabrinaOnline fix contains unrelated changes and doesn't work for me
- [ ] I'm not convinced handling meta-redirects is such an useful feature that it must be handled in that central place, It should probably be moved to the comic module needing it (maybe as a generic helper function)
- [ ] Please remove commits you revert later (CtrlAltDel - git rebase is your friend)

**Comment by DirkReiners** [comment]
Thanks for accepting! 

I wanted to split the pull request, but I didn't see a way to do different requests for different commits, it just let me do one request for all the differences between our repos. How do I do that?

Sabrina works for me, can you send me a log of goes wrong for you?

Redirects: maybe, your decision. I haven't come across any others, but there maybe some. This has the easiest way for me to do it, but if there is a way to do it in the module that would be fine, too. I just don't know how to do that, the modules are still a little magic for me.

Concerning git: [XKCD](https://xkcd.com/1597) ;) I need to look into rebase and see if I can decipher it.

Thanks!

**Comment by TobiX** [comment]
>  I didn't see a way to do different requests for different commits

Pull-Requests always concern a complete branch, so it is advisable to create a branch for each feature and never do a pull-request from your master, since all commits to your master end up in the same pull request.

**Comment by TobiX** [comment]
Please create separate pull requests from separate branches for this (not from master)

**Pull request closed without merging**
