### PR TITLE
Fix for gocomics

### PR DESCRIPTION
**Pull request by hendersj**
Fixes issue #102

### CODE REVIEW

**Comment by hendersj** [comment]
Apologies, didn't realize the second commit was going to pull the s.py update as well - that was intended to be a separate pull request from a separate branch - first time doing a pull request.

**Comment by TobiX** [comment]
That's how pull requests work (for better or worse) - The good thing is that you can amend an ongoing pull request, the bad thing is that you can mess up existing pull request with unrelated changes. I'm going to cherry-pick your change into master.

**Comment by TobiX** [comment]
Sorry, I'm going for a slightly different fix. Thanks for your work (and analysis)!

**Comment by hendersj** [comment]
No problem - glad to help out :)

**Pull request closed without merging**
