### PR TITLE
Dosage as a Docker container

### PR DESCRIPTION
**Pull request by acaranta**
Hi !

First of all thx for your great comics downloader ... it really eases my life ;)

Then here is my contribution : the ability to run (and in an automated easy way) dosage as a docker container.

It does not change your code, it just allows users to build and run dosage as a container.

Hope you'll like it enough to merge ;)

### CODE REVIEW

**Comment by acaranta** [comment]
the travis failure seems (I think) to come from :
```
SexyLosers> ERROR: Patterns ['SEXY LOSERS <A HREF="(.+?)">Latest SL Comic \\(#\\d+\\)</A>'] not found at URL http://www.sexylosers.com/.
```

**Comment by TobiX** [comment]
Why?

**Comment by acaranta** [comment]
@TobiX ... what do you mean "why" ? why what ? :/

**Comment by acaranta** [comment]
BTW, merge your changes concerning SexyLoosers and tadaaa, it builds and travis is happy ! thx ! ;) )

**Comment by TobiX** [comment]
Why should I want to set up a docker container for a single python script? I don't see the usecase for this. What does that give me that I can't do with a virtualenv?

Oh, and running every hour? That's kinda rude to webcomic authors who have to pay their own hosting bill, don't you think?

Oh, and please rebase to get rid of the useless merge commit. (See http://michaeldehaan.net/post/116465000577/understanding-when-to-use-git-rebase)

**Comment by acaranta** [comment]
It really feels good to read your comments ... Really a warm welcome to someone who just wanted to share another way of using a great script, dosage...

I containerized dosage in order to keep my docker hosts as bare metal as possible (aka not installing libraries, virtual environment etc) on the host itself, allowing me not to care on which of these hosts I currently run dosage. The storage volume is link to another container, a Dropbox container to sync with my laptop where I read these comics.

Concerning the 1 hours retry, it was a shot in the dark, an example ... I currently use a 12hours delay...

Now, considering the way you obviously think I did crap, I believe I should close and remove this pull request ...

I was just trying to help if anyone needed to use dosage as a docker container... 
I am quite disappointed:(

**Comment by TobiX** [comment]
I'm really, truly sorry if I have offended you. I wrote the last comment on this pull request in a hurry (and English is not my native language) and wanted it to be short and to the point. I clearly have failed to convey the message I intended. I just wanted to know why one would use docker for a single Python script. I certainly don't understand docker enough to understand all the ways people use it. Just because I personally don't have a use for it doesn't mean I think it's crap.

Please additionally understand that dosage is currently a project I have only little time for, so I try to reduce the maintenance burden for me - this means removing stuff I can not reasonably maintain from the repository (things affected by this: comic descriptions & genres, windows installer) - therefore I'm quite reluctant to add new things I don't use and can't test. I suppose adding the Dockerfile won't hurt much...

**Comment by acaranta** [comment]
Not to worry, I took the Docker idead out of the official repository and made it its own repository (as several other did) :
https://github.com/acaranta/docker-dosage
And thank to that I have an automated build on th docker hub allowing anyone to use it directly a a docker container :
https://hub.docker.com/r/acaranta/dosage/

So nevermind, I did it "on my own" ... even if it still builds against your repository of course, I had no intention to fork the whole project ;)

Anyway, I keep using dosage as it is the only tool I know that does its job so efficiently ;)

**Pull request closed without merging**
