### PR TITLE
Add CadComic (aka Control Alt Delete, aka ctrl-alt-del)

### PR DESCRIPTION
**Pull request by erpbridge**
Reason: Adding CadComic. This is a new scraper. Comic has well defined history.
Testing: Testing has been completed successfully locally.

### CODE REVIEW

**Comment by TobiX** [comment]
Interesting. We had a module for this comic way back, but it was removed because the site was blocking Dosage... I think we should re-introduce it using the same module name now.

**Comment by TobiX** [comment]
For reference: 13a34098547b028093ad3a997ec8729521c3a524 :laughing:

**Comment by TobiX** [comment]
GitHub did strange things when I merged this, so some views might show it as "not merged"...

**Comment by erpbridge** [comment]
Will watch this one... And if they kill scraping at site side, might write a class to run it via archive.org.

The prev button on this site gets wonky too... Will watch.

**Pull request merged**
